version: '3.7'
services:
  trino:
    hostname: trino
    image: 'trinodb/trino:351'
    ports:
      - '8086:8080'
    volumes:
      - ./etc:/usr/lib/trino/etc:ro
    networks:
      - trino-network

  postgres:
    hostname: postgres
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: hiveuser
      POSTGRES_PASSWORD: hivepw
      POSTGRES_DB: metastore_db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "hiveuser", "-d", "metastore_db"]
      interval: 10s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - trino-network

  hive-metastore:
    hostname: hive-metastore
    image: naushadh/hive-metastore:latest
    ports:
      - '9083:9083' # Metastore Thrift
    volumes:
    - ./conf/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
    environment:
      DATABASE_HOST: postgres
      DATABASE_DB: metastore_db
      DATABASE_USER: hiveuser
      DATABASE_PASSWORD: hivepw
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - trino-network

  minio:
    hostname: minio
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./data:/data
    environment:
      MINIO_ROOT_USER: minio_access_key
      MINIO_ROOT_PASSWORD: minio_secret_key
    command: server /data --console-address ":9001"
    networks:
      - trino-network

volumes:
  postgres_data:
  minio-data:
    driver: local

networks:
  trino-network:
    driver: bridge